10X/3/pbmc_5k/:
	mkdir -p $@ && cd $@ && \
	curl -o fastqs.tar http://s3-us-west-2.amazonaws.com/10x.files/samples/cell-exp/3.0.2/5k_pbmc_v3/5k_pbmc_v3_fastqs.tar && \
	tar xvf fastqs.tar -C ./ --strip-components=1

